fix compile error with gcc-9.2.1
Fedora Rawhide (upcoming Fedora 33) has gcc-9.2.1 which causes compiling
archivemount to fail with the following error:

    archivemount.c: In function ‘getLine’:
    archivemount.c:2817:4: error: case label does not reduce to an integer constant
     2817 |    case delim: (*lineptr)[count++] = c;    /* fall through */
          |    ^~~~

The 'delim' integer constant for the switch statement should be a
compile time constant, so either hard-coded or #define'd.

Signed-off-by: Niels de Vos <ndevos@redhat.com>